Branch ab 22937
pt-kompas-media-nusantara/kompas-www-submodules pull request #8
Opened 2021-09-15 12:29 UTC by elpranata

fixes AB#22939

2021-09-15 13:40 UTC, gajayana requested changes

2021-09-15 13:40 UTC, gajayana commented on dev/serve.vue
> +            <ksm-single-caption>(caption base) Lorem ipsum dolor sit, amet consectetur adipisicing elit. Expedita quasi impedit.</ksm-single-caption>
type caption kan dinggo foto + kredit + teks

2021-09-15 13:40 UTC, gajayana commented on src/components/single/Caption.vue
> +        return ['alignnone', 'right'].includes(align)
nilainya seharusnya salah satu dari 'alignnone', 'alignleft', 'alignright' coba cek kode saat ini di www & preview

2021-09-16 03:31 UTC, elpranata commented on src/components/single/Caption.vue
> +        return ['alignnone', 'right'].includes(align)
align: {
      type: String,
      default: 'alignnone',
      validator (align: string) {
        return ['alignnone', 'alignleft', 'alignright'].includes(align)
      }
    }

2021-09-21 01:39 UTC, gajayana approved these changes

2021-09-21 02:04 UTC, merged